CREATE TABLE CLANS(
	CLAN_ID INT NOT NULL AUTO_INCREMENT,
    CLAN_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PKCLAN PRIMARY KEY (CLAN_ID)
);

CREATE TABLE USERS(
	USER_ID INT NOT NULL AUTO_INCREMENT,
    CLAN_ID INT,
    USERNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    CONSTRAINT PKUSER PRIMARY KEY (USER_ID),
    CONSTRAINT FKUSERCLAN FOREIGN KEY (CLAN_ID) REFERENCES CLANS(CLAN_ID)
);

CREATE TABLE HISTORIC(
	MATCH_ID SERIAL,
    USER_ID INT NOT NULL,
    POINTS INT NOT NULL,
    DATE_MATCH TIMESTAMP NOT NULL,
    CONSTRAINT PKHISTORIC PRIMARY KEY(MATCH_ID),
    CONSTRAINT FKHISTORICUSER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);